server:
  port: 8010

spring:
  application:
    name: turbine

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

turbine:
  app-config: user, order
  cluster-name-expression: new String("default")
