server:
  port: 9030

spring:
  application:
    name: commodity
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/commodity?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    sentinel:
      master: host6379
      nodes: 127.0.0.1:16379,127.0.0.1:16380
    redisson:
      config: classpath:redisson.json
    url: 127.0.0.1
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

tx-lcn:
  springcloud:
    loadbalance:
      enabled: true

ribbon:
  MaxAutoRetriesNextServer: 0

logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG
